modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="storydanilka"
version="1.0.0"
displayName="YouDanilka"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="kabancik166, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.storydanilka]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.storydanilka]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storydanilka]]
    modId="particlepresets"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

